# Generated by Django 3.2.7 on 2021-09-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suite.division'),
        ),
    ]
